version: '3.8'
services:
  lightricks-finetune:
    image: aeorlov/ados-workspace-cuda13.0:v.0.0.5
    ports:
      - "8889:8888"
    volumes:
      - checkpoints:/mnt/data
    environment:
      - JUPYTER_TOKEN=lightricks
    command: >
     /bin/bash -c "jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --notebook-dir=/mnt/data"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  checkpoints:
