version: '3.8'
services:
  lightricks-finetune:
    image: aeorlov/ados-workspace-cuda13.0:v.0.0.5
    user: root
    volumes:
      - checkpoints:/mnt/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  checkpoints:
