version: '3.8'
services:
  lightricks-finetune:
    image: aeorlov/ados-workspace-cuda13.0:v.0.0.5
    user: root
    ports:
      - "8889:8888"
    volumes:
      - checkpoints:/mnt/data
    command: >
      /bin/bash -c "pip install uv --break-system-packages && uv pip install jupyterlab --system
--break-system-packages && jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
--notebook-dir=/mnt/data --NotebookApp.token='' --NotebookApp.password=''"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  volumes:
    checkpoints:
